// ACCOUNTS
export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST';
export const ACCOUNTS_SUCCESS = 'ACCOUNTS_SUCCESS';
export const ACCOUNTS_FAILURE = 'ACCOUNTS_FAILURE';
export const ADD_DELEGATE_ACCOUNT_REQUEST = 'ADD_DELEGATE_ACCOUNT_REQUEST';
export const ADD_DELEGATE_ACCOUNT_SUCCESS = 'ADD_DELEGATE_ACCOUNT_SUCCESS';
export const ADD_DELEGATE_ACCOUNT_FAILURE = 'ADD_DELEGATE_ACCOUNT_FAILURE';
export const DELETE_DELEGATE_ACCOUNT_REQUEST = 'DELETE_DELEGATE_ACCOUNT_REQUEST';
export const DELETE_DELEGATE_ACCOUNT_SUCCESS = 'DELETE_DELEGATE_ACCOUNT_SUCCESS';
export const DELETE_DELEGATE_ACCOUNT_FAILURE = 'DELETE_DELEGATE_ACCOUNT_FAILURE';

// ACCOUNT ROLES
export const ROLES_REQUEST = 'ROLES_REQUEST';
export const ROLES_SUCCESS = 'ROLES_SUCCESS';
export const ROLES_FAILURE = 'ROLES_FAILURE';
export const ADD_ROLE_REQUEST = 'ADD_ROLE_REQUEST';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAILURE = 'ADD_ROLE_FAILURE';
export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';

// WISHLIST
export const ADD_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAILURE = 'ADD_WISHLIST_FAILURE';

export const ADD_CELLAR_REQUEST = 'ADD_CELLAR_REQUEST';
export const ADD_CELLAR_SUCCESS = 'ADD_CELLAR_SUCCESS';
export const ADD_CELLAR_FAILURE = 'ADD_CELLAR_FAILURE';

export const LOAD_CELLAR_REQUEST = 'LOAD_CELLAR_REQUEST';
export const LOAD_CELLAR_SUCCESS = 'LOAD_CELLAR_SUCCESS';
export const LOAD_CELLAR_FAILURE = 'LOAD_CELLAR_FAILURE';

export const ADD_CELLAR_LOCATION_REQUEST = 'ADD_CELLAR_LOCATION_REQUEST';
export const ADD_CELLAR_LOCATION_SUCCESS = 'ADD_CELLAR_LOCATION_SUCCESS';
export const ADD_CELLAR_LOCATION_FAILURE = 'ADD_CELLAR_LOCATION_FAILURE';

export const LOAD_CELLAR_LOCATIONS_REQUEST = 'LOAD_CELLAR_LOCATIONS_REQUEST';
export const LOAD_CELLAR_LOCATIONS_SUCCESS = 'LOAD_CELLAR_LOCATIONS_SUCCESS';
export const LOAD_CELLAR_LOCATIONS_FAILURE = 'LOAD_CELLAR_LOCATIONS_FAILURE';

export const ADD_CELLAR_LOCATION_BIN_REQUEST = 'ADD_CELLAR_LOCATION_BIN_REQUEST';
export const ADD_CELLAR_LOCATION_BIN_SUCCESS = 'ADD_CELLAR_LOCATION_BIN_SUCCESS';
export const ADD_CELLAR_LOCATION_BIN_FAILURE = 'ADD_CELLAR_LOCATION_BIN_FAILURE';

export const LOAD_CELLAR_LOCATION_BINS_REQUEST = 'LOAD_CELLAR_LOCATION_BINS_REQUEST';
export const LOAD_CELLAR_LOCATION_BINS_SUCCESS = 'LOAD_CELLAR_LOCATION_BINS_SUCCESS';
export const LOAD_CELLAR_LOCATION_BINS_FAILURE = 'LOAD_CELLAR_LOCATION_BINS_FAILURE';

//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//PERMISSIONS
export const PERMISSIONS_REQUEST = 'PERMISSIONS_REQUEST';
export const PERMISSIONS_SUCCESS = 'PERMISSIONS_SUCCESS';
export const PERMISSIONS_FAILURE = 'PERMISSIONS_FAILURE';

//PRODUCTS
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

//SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

//PROPERTY
export const PROPERTY_REQUEST = 'PROPERTY_REQUEST';
export const PROPERTY_SUCCESS = 'PROPERTY_SUCCESS';
export const PROPERTY_FAILURE = 'PROPERTY_FAILURE';

//PROPERTY TYPE
export const PROPERTY_TYPE_REQUEST = 'PROPERTY_TYPE_REQUEST';
export const PROPERTY_TYPE_SUCCESS = 'PROPERTY_TYPE_SUCCESS';
export const PROPERTY_TYPE_FAILURE = 'PROPERTY_TYPE_FAILURE';

//PROPERTY PROJECT
export const PROPERTY_PROJECT_REQUEST = 'PROPERTY_PROJECT_REQUEST';
export const PROPERTY_PROJECT_SUCCESS = 'PROPERTY_PROJECT_SUCCESS';
export const PROPERTY_PROJECT_FAILURE = 'PROPERTY_PROJECT_FAILURE';

//PROPERTY PROJECT TYPE
export const PROPERTY_PROJECT_TYPE_REQUEST = 'PROPERTY_PROJECT_TYPE_REQUEST';
export const PROPERTY_PROJECT_TYPE_SUCCESS = 'PROPERTY_PROJECT_TYPE_SUCCESS';
export const PROPERTY_PROJECT_TYPE_FAILURE = 'PROPERTY_PROJECT_TYPE_FAILURE';

//PROPERTY PROJECT COMMENT
export const PROPERTY_PROJECT_COMMENT_REQUEST = 'PROPERTY_PROJECT_COMMENT_REQUEST';
export const PROPERTY_PROJECT_COMMENT_SUCCESS = 'PROPERTY_PROJECT_COMMENT_SUCCESS';
export const PROPERTY_PROJECT_COMMENT_FAILURE = 'PROPERTY_PROJECT_COMMENT_FAILURE';

//PROPERTY PROJECT TODO
export const PROPERTY_PROJECT_TODO_REQUEST = 'PROPERTY_PROJECT_TODO_REQUEST';
export const PROPERTY_PROJECT_TODO_SUCCESS = 'PROPERTY_PROJECT_TODO_SUCCESS';
export const PROPERTY_PROJECT_TODO_FAILURE = 'PROPERTY_PROJECT_TODO_FAILURE';

//PROPERTY PROJECT HISTORY
export const PROPERTY_PROJECT_HISTORY_REQUEST = 'PROPERTY_PROJECT_HISTORY_REQUEST';
export const PROPERTY_PROJECT_HISTORY_SUCCESS = 'PROPERTY_PROJECT_HISTORY_SUCCESS';
export const PROPERTY_PROJECT_HISTORY_FAILURE = 'PROPERTY_PROJECT_HISTORY_FAILURE';

//PROPERTY CONTACT
export const PROPERTY_CONTACT_REQUEST = 'PROPERTY_CONTACT_REQUEST';
export const PROPERTY_CONTACT_SUCCESS = 'PROPERTY_CONTACT_SUCCESS';
export const PROPERTY_CONTACT_FAILURE = 'PROPERTY_CONTACT_FAILURE';

//PROPERTY CONTACT TYPE
export const PROPERTY_CONTACT_TYPE_REQUEST = 'PROPERTY_CONTACT_TYPE_REQUEST';
export const PROPERTY_CONTACT_TYPE_SUCCESS = 'PROPERTY_CONTACT_TYPE_SUCCESS';
export const PROPERTY_CONTACT_TYPE_FAILURE = 'PROPERTY_CONTACT_TYPE_FAILURE';

//PROPERTY LIABILITY
export const PROPERTY_LIABILITY_REQUEST = 'PROPERTY_LIABILITY_REQUEST';
export const PROPERTY_LIABILITY_SUCCESS = 'PROPERTY_LIABILITY_SUCCESS';
export const PROPERTY_LIABILITY_FAILURE = 'PROPERTY_LIABILITY_FAILURE';

//PROPERTY TRANSACTION
export const PROPERTY_TRANSACTION_REQUEST = 'PROPERTY_TRANSACTION_REQUEST';
export const PROPERTY_TRANSACTION_SUCCESS = 'PROPERTY_TRANSACTION_SUCCESS';
export const PROPERTY_TRANSACTION_FAILURE = 'PROPERTY_TRANSACTION_FAILURE';

//PROPERTY REQUEST
export const PROPERTY_REQUEST_REQUEST = 'PROPERTY_REQUEST_REQUEST';
export const PROPERTY_REQUEST_SUCCESS = 'PROPERTY_REQUEST_SUCCESS';
export const PROPERTY_REQUEST_FAILURE = 'PROPERTY_REQUEST_FAILURE';

//PROPERTY ASSET
export const PROPERTY_ASSET_REQUEST = 'PROPERTY_ASSET_REQUEST';
export const PROPERTY_ASSET_SUCCESS = 'PROPERTY_ASSET_SUCCESS';
export const PROPERTY_ASSET_FAILURE = 'PROPERTY_ASSET_FAILURE';

//PROPERTY ACCOUNT
export const PROPERTY_ACCOUNT_REQUEST = 'PROPERTY_ACCOUNT_REQUEST';
export const PROPERTY_ACCOUNT_SUCCESS = 'PROPERTY_ACCOUNT_SUCCESS';
export const PROPERTY_ACCOUNT_FAILURE = 'PROPERTY_ACCOUNT_FAILURE';

//PROPERTY DASHBOARD
export const PROPERTY_DASHBOARD_REQUEST = 'PROPERTY_DASHBOARD_REQUEST';
export const PROPERTY_DASHBOARD_SUCCESS = 'PROPERTY_DASHBOARD_SUCCESS';
export const PROPERTY_DASHBOARD_FAILURE = 'PROPERTY_DASHBOARD_FAILURE';

//DATAGRID
export const DATAGRID_CHANGETYPE = 'DATAGRID_CHANGETYPE';
export const DATAGRID_LAZYLOAD = 'DATAGRID_LAZYLOAD';
export const DATAGRID_ROW_ACTION = 'DATAGRID_ROW_ACTION';

// PROPERTY TYPES CONST
export const PROPERTY_TYPES_LIST = [
    'House',
    'Apartment',
    'Bungalow',
    'Condo',
    'Villa',
    'Treehouse',
    'Cabin',
    'Castle',
    'Cave',
    'Chalet',
    'Lighthouse',
    'Tent',
    'Townhouse',
    'Yurt',
    'Floating property'
];

// PROPERTY AMENITIES CONST
export const PROPERTY_AMENITIES_LIST = [
    'Cinema',
    'Heated Pool',
    'Jacuzzi',
];

// PROPERTY BEDROOM AMENITIES CONST
export const PROPERTY_BEDROOM_AMENITIES_LIST = [
    'TV',
    'Internet'
];

// PROPERTY BATHROOM AMENITIES CONST
export const PROPERTY_BATHROOM_AMENITIES_LIST = [
    'Toilet',
    'Shower'
];

//WINES
export const WINES_REQUEST = 'WINES_REQUEST';
export const WINES_SUCCESS = 'WINES_SUCCESS';
export const WINES_FAILURE = 'WINES_FAILURE';
export const WINES_DASHBOARD_REQUEST = 'WINES_DASHBOARD_REQUEST';
export const WINES_DASHBOARD_SUCCESS = 'WINES_DASHBOARD_SUCCESS';
export const WINES_DASHBOARD_FAILURE = 'WINES_DASHBOARD_FAILURE';
export const ADD_WINE_REQUEST = 'ADD_WINE_REQUEST';
export const ADD_WINE_SUCCESS = 'ADD_WINE_SUCCESS';
export const ADD_WINE_FAILURE = 'ADD_WINE_FAILURE';
export const EDIT_WINE_REQUEST = 'EDIT_WINE_REQUEST';
export const EDIT_WINE_SUCCESS = 'EDIT_WINE_SUCCESS';
export const EDIT_WINE_FAILURE = 'EDIT_WINE_FAILURE';
export const DRINK_WINE_REQUEST = 'DRINK_WINE_REQUEST';
export const DRINK_WINE_SUCCESS = 'DRINK_WINE_SUCCESS';
export const DRINK_WINE_FAILURE = 'DRINK_WINE_FAILURE';
export const SORT_WINES_REQUEST = 'SORT_WINES_REQUEST';
export const SORT_WINES_SUCCESS = 'SORT_WINES_SUCCESS';
export const SORT_WINES_FAILURE = 'SORT_WINES_FAILURE';
export const WINES_ACCOUNT_REQUEST = 'WINES_ACCOUNT_REQUEST';
export const WINES_ACCOUNT_SUCCESS = 'WINES_ACCOUNT_SUCCESS';
export const WINES_ACCOUNT_FAILURE = 'WINES_ACCOUNT_FAILURE';

//STAMPS
export const STAMPS_REQUEST = 'STAMPS_REQUEST';
export const STAMPS_SUCCESS = 'STAMPS_SUCCESS';
export const STAMPS_FAILURE = 'STAMPS_FAILURE';
export const STAMPS_ACCOUNT_REQUEST = 'STAMPS_ACCOUNT_REQUEST';
export const STAMPS_ACCOUNT_SUCCESS = 'STAMPS_ACCOUNT_SUCCESS';
export const STAMPS_ACCOUNT_FAILURE = 'STAMPS_ACCOUNT_FAILURE';

//ARTS
export const ARTS_REQUEST = 'ARTS_REQUEST';
export const ARTS_SUCCESS = 'ARTS_SUCCESS';
export const ARTS_FAILURE = 'ARTS_FAILURE';
export const ARTS_ACCOUNT_REQUEST = 'ARTS_ACCOUNT_REQUEST';
export const ARTS_ACCOUNT_SUCCESS = 'ARTS_ACCOUNT_SUCCESS';
export const ARTS_ACCOUNT_FAILURE = 'ARTS_ACCOUNT_FAILURE';
export const ARTS_DASHBOARD_REQUEST = 'ARTS_DASHBOARD_REQUEST';
export const ARTS_DASHBOARD_SUCCESS = 'ARTS_DASHBOARD_SUCCESS';
export const ARTS_DASHBOARD_FAILURE = 'ARTS_DASHBOARD_FAILURE';
export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE';
export const GET_LOCATIONS_REQUEST = 'GET_LOCATIONS_REQUEST';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';
export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';
export const ADD_ART_GROUP_REQUEST = 'ADD_ART_GROUP_REQUEST';
export const ADD_ART_GROUP_SUCCESS = 'ADD_ART_GROUP_SUCCESS';
export const ADD_ART_GROUP_FAILURE = 'ADD_ART_GROUP_FAILURE';
export const ADD_ART_ACCOUNT_REQUEST = 'ADD_ART_ACCOUNT_REQUEST';
export const ADD_ART_ACCOUNT_SUCCESS = 'ADD_ART_ACCOUNT_SUCCESS';
export const ADD_ART_ACCOUNT_FAILURE = 'ADD_ART_ACCOUNT_FAILURE';
export const ADD_ART_LOCATIONS_REQUEST = 'ADD_ART_LOCATIONS_REQUEST';
export const ADD_ART_LOCATIONS_SUCCESS = 'ADD_ART_LOCATIONS_SUCCESS';
export const ADD_ART_LOCATIONS_FAILURE = 'ADD_ART_LOCATIONS_FAILURE';
export const DELETE_ART_ACCOUNT_REQUEST = 'DELETE_ART_ACCOUNT_REQUEST';
export const DELETE_ART_ACCOUNT_SUCCESS = 'DELETE_ART_ACCOUNT_SUCCESS';
export const DELETE_ART_ACCOUNT_FAILURE = 'DELETE_ART_ACCOUNT_FAILURE';

//COINS
export const COINS_REQUEST = 'COINS_REQUEST';
export const COINS_SUCCESS = 'COINS_SUCCESS';
export const COINS_FAILURE = 'COINS_FAILURE';
export const COINS_ACCOUNT_REQUEST = 'COINS_ACCOUNT_REQUEST';
export const COINS_ACCOUNT_SUCCESS = 'COINS_ACCOUNT_SUCCESS';
export const COINS_ACCOUNT_FAILURE = 'COINS_ACCOUNT_FAILURE';

//RECORDS
export const RECORDS_REQUEST = 'RECORDS_REQUEST';
export const RECORDS_SUCCESS = 'RECORDS_SUCCESS';
export const RECORDS_FAILURE = 'RECORDS_FAILURE';
export const RECORDS_ACCOUNT_REQUEST = 'RECORDS_ACCOUNT_REQUEST';
export const RECORDS_ACCOUNT_SUCCESS = 'RECORDS_ACCOUNT_SUCCESS';
export const RECORDS_ACCOUNT_FAILURE = 'RECORDS_ACCOUNT_FAILURE';

//Unique Key
export const UNIQUE_KEY = 'nNLiCY7r';
